### ISSUE TITLE
Sign up using independent email and password

### ISSUE THREAD

**Issue by antonvorobyev** [binrush/thousands#25]

**Comment by binrush** [comment]
Why couldn't one just create account on southural.ru if he doesn't want to use social accounts?

**Comment by antonvorobyev** [comment]
@binrush, 

I don't use southural.ru. It is not interesting for me. And thousands looks like idependent and selfsufficient service. I think this thing is true for everyone.

And it is not usable "go to service thousands, see cumbersomeness problem with registration, after it go to southural.ru, walk trhough register workflow of southural.ru, return to thousands, bla-bla-bla". It is strange.

If needs to promote southural.ru using thousands... Can we intergrate/embed signup form of southural.ru into thousands? Or link to signup page of southural.ru, at least.

**Comment by kagel** [comment]
Welcome aboard, @antonvorobyev

**Comment by binrush** [comment]
We don't need to promote southural.ru, but we either don't want to add redundant functionality. I agree that registering in southural.ru and returning back manually is annoying, but I think it's a rather rare case. Most people just use social accounts.

I think, adding link to southural.ru registration with some comment on auth popup is good idea

**Comment by antonvorobyev** [comment]
@kagel, thank you!

"Or link to signup page of southural.ru, at least" - Ok, this line, actually, doesn't reflect that I wanted to tell. Words "with some comment on auth popup is good idea" is right way for minimal usability.

I will think that I can offer you in this way.

**Comment by binrush** [comment]
Added link to registration and comment to login widget
