### ISSUE TITLE
Perform stress test

### ISSUE THREAD

**Issue by binrush** [binrush/thousands#30]
Before release, we should perform stress test to ensure that site can handle rather many user requests

**Comment by antonvorobyev** [comment]
Take in view about tiles reads limit of default map

**Comment by binrush** [comment]
Thank you, Anton. I think, we should test only our site endpoints, without touching tile sources.

**Comment by varnie** [comment]
Yes, I fully agree with Anton. Undoubtedly we should thoroughly work out the aforementioned case.
Thank you for nitpicking, Anton.

**Comment by varnie** [comment]
glad it is sorta resolved. good job!
